### ISSUE TITLE
Add 2way databinding support `@={}` 

### ISSUE THREAD

**Issue by shiraji** [shiraji/databinding-support#12]
Related to #2 and #3, add `@={}` support. Would be nice if this plugin switch `@{}` with `@={}` and vice versa

### TODO

- [x] Switch to 2 way databinding
- [x] Switch to databinding tag
- [ ] Add 2 way databinding
